--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/koningcool/loadallworlds
build-by-default: true
branches:
- master
- 11-configyml-resets-itself-every-time-the-server-starts
projects:
  loadallworlds:
    path: ""
    icon: "icon.png"
...
