--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/koningcool/loadallworlds
build-by-default: true
branches:
- master
- noupdatenotifier
projects:
  loadallworlds:
    path: ""
    icon: "icon.png"
    libs:
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
...
